### ISSUE TITLE
Add club not visible on homepage when not logged in

### ISSUE THREAD

**Issue by Ssunoo2** [rio-connect/rio-connect#114]

**Comment by jakeswalker** [comment]
The landing page shows "Get Started" instead of "Create a Club" when logged-out. When logged-in, the page shows "Create a Club."

![Image](https://user-images.githubusercontent.com/122703805/235271590-41794a74-1a92-40d8-8824-a098682f02d0.png)

![Image](https://user-images.githubusercontent.com/122703805/235271581-459847e8-d7d5-4a8c-ac93-52d904065acf.png)
